### PR TITLE
Changed All polish sumbols like 'ś' to 's'

### PR DESCRIPTION
**Pull request by dearminder**
because of bugged that showed those symbols completely incorrect

### CODE REVIEW

**Comment by genboy** [comment]
Thank you @dearminder, i will keep a copy of the original text - think i should [learn more](https://www.google.com/search?client=firefox-b-d&q=polish+in+utf+8) about those symbols to get the translations correctly through json and php.

**Comment by genboy** [comment]
:)  @dearminder, i learned how to fix this! 
Minecraft 23-4-2019 22_21_37

Many php programmers had the same problem, an italian has made a piece of code that seems to work! It is still a bit experimental, i should also test Festival can handle chinees etc. with this.

**Comment by dearminder** [comment]
Wow congrats. Sadly I still preffer no symbols one but only because Minecraft badly support these languages and makes characters smaller and thinner. even on java Minecraft it looks like this but bit diffrent. it makes only this single letter looks like this

**Comment by genboy** [comment]
Ok, i understand - there is now a separate translation branch for [plain characters](https://github.com/genboy/Festival/tree/Tranlations_plain_char), without the special encoding. Can you use the branch together with the devtools plugin (to use Festival from an unpacked folder) or do you need a .phar file?

**Comment by dearminder** [comment]
ya sure give me a second

**Comment by genboy** [comment]
The branch will stay there, no hurry

**Comment by dearminder** [comment]
damn i forgot i updated mc. I will test when pmmp will get updated

**Pull request merged**
